name: Build and Deploy theme on push

on:
  push
    
jobs:
  push-shopify-theme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push Shopify theme
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_FLAG_STORE: ${{ vars.SHOPIFY_STORE }}
          SHOPIFY_FLAG_THEME_ID: ${{ vars.THEME_ID }}
        run: npx @shopify/cli@latest theme push

