name: Build and Deploy theme on push

on: push

jobs:
  push-shopify-theme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check environment variables
        run: |
          if [ -z "${{ secrets.SHOPIFY_PASSWORD }}" ]; then
            echo "❌ SHOPIFY_PASSWORD secret is not set"
            exit 1
          fi
          if [ -z "${{ vars.SHOPIFY_STORE }}" ]; then
            echo "❌ SHOPIFY_STORE variable is not set"
            exit 1
          fi
          if [ -z "${{ vars.THEME_ID }}" ]; then
            echo "❌ THEME_ID variable is not set"
            exit 1
          fi
          echo "✅ All required environment variables are set"
          echo "Store: ${{ vars.SHOPIFY_STORE }}"
          echo "Theme ID: ${{ vars.THEME_ID }}"
          echo "Token starts with: ${SHOPIFY_PASSWORD:0:10}..."

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Push Shopify theme
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_FLAG_STORE: ${{ vars.SHOPIFY_STORE }}
          SHOPIFY_FLAG_THEME_ID: ${{ vars.THEME_ID }}
        run: |
          echo "Starting Shopify theme push..."
          echo "Store: $SHOPIFY_FLAG_STORE"
          echo "Theme ID: $SHOPIFY_FLAG_THEME_ID"
          npx @shopify/cli@latest theme push --verbose
